example_project/urls.py
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
    url(r'', include('squattour.urls', namespace='squattour', app_name='squattour')),
    url(r'^admin/', include(admin.site.urls)),
    url(r'^account/', include('allauth.urls')),
    url(r'^pages/?', include('django.contrib.flatpages.urls')),
]

squattour/urls.py
from django.conf.urls import include, url

from . import views

app_name = 'squattour'

urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^contacts/$', views.contacts, name='contacts'),
    url(r'^map/$', views.show_map, name='map'),
    url(r'^export/friends.(?P<fmt>[\w]+)$', views.export, name='export'),
    url(r'^export/(?P<token>[\w]{32})/friends.(?P<fmt>[\w]+)$',
        views.export, name='export'),
    url(r'^contacts/import/$', views.import_contacts, name='import'),
    url(r'^contacts/import/social/$',
        views.import_social, name='import_social'),
    url(r'^contacts/import/social/(?P<account>[0-9]+)/$',
        views.import_social, name='import_social'),
    url(r'^contacts/import/social/(?P<account>[0-9]+)/status$',
        views.poll_import_status, name='poll_import_status'),
]

squattour/models.py
import uuid

from allauth.socialaccount.models import SocialAccount
from django.conf import settings
from django.db import models


class Contact(models.Model):
    user = models.ForeignKey(
        settings.AUTH_USER_MODEL, related_name="squattour_contacts",
        on_delete=models.CASCADE)
    name = models.CharField(max_length=255)
    address = models.TextField(null=True)
    latitude = models.FloatField(max_length=100, null=True, blank=True)
    longitude = models.FloatField(max_length=100, null=True, blank=True)
    show = models.BooleanField(default=True)

    def __str__(self):
        return self.name

    @property
    def best_address(self):
        return self.address or self.social.address

    @property
    def best_latitude(self):
        return self.latitude or self.social.latitude

    @property
    def best_longitude(self):
        return self.longitude or self.social.longitude

    @property
    def coordinates(self):
        return "{},{}".format(self.best_longitude, self.best_latitude)

    @property
    def photo_urls(self):
        if self.social.photo_url:
            return [self.social.photo_url]
        else:
            return []


class GroupContact:

    def __init__(self, *args):
        self._contacts = args
        for contact in self._contacts:
            if not isinstance(contact, Contact):
                raise ValueError(
                    "A GroupContact can only contain Contact objects")
        self.name = ", ".join([c.name for c in self._contacts])
        for attribute in ("best_latitude", "best_longitude"):
            if len(set([getattr(c, attribute) for c in self._contacts])) != 1:
                raise ValueError(
                    "All Contacts must have the same %s" % attribute)
            setattr(self, attribute, getattr(self._contacts[0], attribute))
        self.coordinates = "{},{}".format(
            self.best_longitude, self.best_latitude)
        # It may be the same address but spelled differently.
        self.best_address = self._contacts[0].best_address

    def __len__(self):
        return len(self._contacts)

    @property
    def photo_urls(self):
        photos = []
        for contact in self._contacts:
            if contact.social.photo_url:
                photos.append(contact.social.photo_url)
        return photos


class SocialContact(models.Model):
    contact = models.OneToOneField(
        Contact, related_name="social", on_delete=models.CASCADE)
    socialaccount = models.ForeignKey(
        SocialAccount, related_name="squattour_contacts",
        on_delete=models.CASCADE)
    social_uid = models.CharField(max_length=255)
    address = models.TextField(null=True, editable=False)
    latitude = models.FloatField(max_length=100, null=True, editable=False)
    longitude = models.FloatField(max_length=100, null=True, editable=False)
    photo_url = models.CharField(max_length=255, null=True, blank=True)

    def __str__(self):
        return "{} ({})".format(
            self.contact.name, self.socialaccount.provider)


class Profile(models.Model):
    user = models.OneToOneField(
        settings.AUTH_USER_MODEL,
        related_name="squattour_profile",
        on_delete=models.CASCADE)
    token = models.UUIDField(default=uuid.uuid4, editable=False, db_index=True)

squattour/views.py
import json
import uuid

from allauth.socialaccount.models import SocialAccount, SocialApp
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.core.exceptions import PermissionDenied, SuspiciousOperation
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.core.urlresolvers import reverse
from django.http import HttpResponse
from django.shortcuts import get_object_or_404, render, redirect
from django.template import loader, Context, Template

from .models import Contact, GroupContact, Profile
from .lib.mapping import get_service
from .lib.contact import get_connector


def index(request):
    context = {}
    return render(request, 'squattour/index.html', context)


@login_required
def contacts(request):
    if request.method == "POST":
        contact = get_object_or_404(Contact, pk=request.POST["contact"])
        if request.POST["action"] == "hide":
            contact.show = False
            contact.save()
        elif request.POST["action"] == "show":
            contact.show = True
            contact.save()
        elif request.POST["action"] == "reimport":
            pass # TODO
        return redirect("squattour:contacts")

    contacts = Contact.objects.filter(
        user=request.user, show=True
        ).order_by("name").select_related("social").all()
    paginator = Paginator(contacts, 50)
    page = request.GET.get('page')
    try:
        contacts = paginator.page(page)
    except PageNotAnInteger:
        contacts = paginator.page(1)
    except EmptyPage:
        # If page is out of range (e.g. 9999), deliver last page of results.
        contacts = paginator.page(paginator.num_pages)

    social_apps = {}
    for contact in contacts:
        if not contact.social:
            continue
        provider = contact.social.socialaccount.provider
        if provider not in social_apps:
            social_apps[provider] = SocialApp.objects.get_current(
                provider, request)
        contact.social_app = social_apps[provider]

    context = {
        "contacts": contacts,
    }
    return render(request, 'squattour/contacts.html', context)


@login_required
def import_contacts(request):
    context = {
        "accounts": SocialAccount.objects.filter(user=request.user),
        }
    return render(request, 'squattour/import.html', context)


@login_required
def show_map(request):
    service = get_service()
    context = {
        "service": service,
        "kml_url": request.build_absolute_uri(
            reverse("squattour:export", kwargs={
                    "token": request.user.squattour_profile.token.hex,
                    "fmt": "kml",
                    })
            ),
        "geojson_url": request.build_absolute_uri(
            reverse("squattour:export", kwargs={
                    "token": request.user.squattour_profile.token.hex,
                    "fmt": "json",
                    })
            ),
    }
    return render(request, service.template, context)


def export(request, token=None, fmt="kml"):
    # Export to KML or GeoJSON
    if request.user.is_authenticated:
        user = request.user
    else:
        try:
            user = Profile.objects.filter(token=uuid.UUID(hex=token)).one()
        except Profile.DoesNotExist:
            raise PermissionDenied
    all_contacts = list(Contact.objects.filter(
            user=user, show=True
        ).exclude(
            latitude=None, social__latitude=None
        ).exclude(
            longitude=None, social__longitude=None
        ).select_related("social"))

    # Merge contacts at the same address
    contacts_by_coords = {}
    for contact in all_contacts:
        if contact.coordinates not in contacts_by_coords:
            contacts_by_coords[contact.coordinates] = []
        contacts_by_coords[contact.coordinates].append(contact)
    contacts = []
    for coordinates, contact_list in contacts_by_coords.items():
        if len(contact_list) == 1:
            contacts.append(contact_list[0])
        else:
            contacts.append(GroupContact(*contact_list))


    response = HttpResponse()

    if fmt == "kml":
        # Create the HttpResponse object with the appropriate header.
        response.content_type = 'application/vnd.google-earth.kml+xml'
        t = loader.get_template('squattour/kml.xml')
        c = Context({"contacts": contacts})
        response.write(t.render(c))

    elif fmt == "json":
        popup_template = Template("""
            <div class="squattour-popup">
            <h1>{{ contact.name }}</h1>
            <p>
                {% for photo_url in contact.photo_urls %}
                    <img src="{{ photo_url }}" class="photo" />
                {% endfor %}
                {{ contact.best_address }}
            </p>
            </div>
            """)
        data = {"type": "FeatureCollection", "features": []}
        for contact in contacts:
            weight = len(contact) if isinstance(contact, GroupContact) else 1
            data["features"].append({
                "type": "Feature",
                "geometry": {
                    "type": "Point",
                    "coordinates": [
                        contact.best_longitude,
                        contact.best_latitude
                        ],
                    },
                "properties": {
                    "name": contact.name,
                    "popupContent": popup_template.render(Context({
                        "contact": contact})),
                    "weight": weight,
                    }
                })
        response = HttpResponse(content_type='application/javascript')
        response.write(json.dumps(data, indent=2))

    response['Content-Disposition'] = \
        'attachment; filename="friends.{}"'.format(fmt)
    return response


@login_required
def import_social(request, account):
    social_account = get_object_or_404(SocialAccount, pk=int(account))
    if social_account.user != request.user:
        raise PermissionDenied
    social_app = SocialApp.objects.get_current(
        social_account.provider, request)
    if "import" not in request.session:
        request.session["import"] = {"status": "init", "contacts": []}
    return render(request, 'squattour/import_social.html', {
        "social_account": social_account,
        "social_app": social_app,
        })


@login_required
def poll_import_status(request, account):
    social_account = get_object_or_404(SocialAccount, pk=int(account))
    if social_account.user != request.user:
        raise PermissionDenied

    if request.method == "POST":
        if request.session["import"]["status"] != "init":
            raise SuspiciousOperation
        # Start the process
        request.session["import"] = {"status": "working", "contacts": []}
        request.session.save()
        social_app = SocialApp.objects.get_current(
            social_account.provider, request)
        connector = get_connector(social_account, social_app)
        def add_to_session(contact):
            request.session["import"]["contacts"].append(contact.contact.name)
            request.session.save()
        connector.import_all(callback=add_to_session)
        messages.success(
            request,
            "%s contacts successfully imported."
            % len(request.session["import"]["contacts"]))
        del request.session["import"]
        return HttpResponse(json.dumps({"status": "done"}),
                            content_type='application/javascript')

    else:
        if "import" in request.session:
            return HttpResponse(json.dumps(request.session["import"]),
                                content_type='application/javascript')
        else:
            return HttpResponse(json.dumps({"status": "done"}),
                                content_type='application/javascript')

squattour/templates/squattour/base.html
{% load i18n %}
{% load staticfiles %}
{% load navigation %}
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->
    <title>{% block head_title %}Squat Tour{% endblock %}</title>

    <!-- Bootstrap -->
    <!-- Latest compiled and minified CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">

    <!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/html5shiv/3.7.3/html5shiv.min.js"></script>
      <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->

    <link rel="stylesheet" href="{% static 'squattour/css/main.css' %}">

    {% block extra_head %}
    {% endblock %}
  </head>
  <body>
    {% block body %}

    <nav class="navbar navbar-default navbar-static-top">
        <div class="container">
            <!-- Brand and toggle get grouped for better mobile display -->
            <div class="navbar-header">
                <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar-collapse-1" aria-expanded="false">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a class="navbar-brand logo" href="{% url "squattour:index" %}" title="{% trans 'Home' %}">
                    <img src="{% static "squattour/img/logo-50.png" %}" />
                </a>
                <a class="navbar-brand" href="{% url "squattour:index" %}" title="{% trans 'Home' %}">
                    Squat Tour
                </a>
            </div>
            <!-- Collect the nav links, forms, and other content for toggling -->
            <div class="collapse navbar-collapse" id="navbar-collapse-1">
                <!-- Navigation links -->
                <ul class="nav navbar-nav">
                    {% nav_link view_name="squattour:contacts" label="Contacts" icon="user" %}
                    {% nav_link view_name="squattour:map" label="Map" icon="map-marker" %}
                </ul>
                <ul class="nav navbar-nav navbar-right">
                    <!-- Extra nav links -->
                    {% include 'nav/extra_links.html' %}
                    <!-- Account & Authentication -->
                    {% include 'nav/auth_menu.html' %}
                </ul>
            </div>
        </div>
    </nav>

    <div class="container">

    {% if messages %}
    <div class="row">
    {% for msg in messages %}
        <div class="alert alert-{{ msg.tags }}">{{ msg }}</div>
    {% endfor %}
    </div>
    {% endif %}

    {% block content %}
    {% endblock %}

    </div>
    {% endblock body %}

    <footer class="footer">
        <div class="container">
            <p class="text-center">
                <a href="https://gitlab.com/abompard/squattour/">Squat Tour</a>
                is Free Software,
                <a href="http://www.gnu.org/licenses/agpl-3.0.html">read your rights</a>.
            </p>
        </div>
    </footer>

    <!-- jQuery (necessary for Bootstrap's JavaScript plugins) -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>
    <!-- Latest compiled and minified JavaScript -->
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>
    <script src="{% static 'squattour/js/main.js' %}"></script>

    {% block extra_body %}
    {% endblock %}

    {% include 'squattour/bottom.html' %}
  </body>
</html>

squattour/templates/squattour/bottom.html
{# This markup will appear before the </body> tag #}

squattour/templates/squattour/contacts.html
{% extends "squattour/base.html" %}

{% load i18n %}

{% block head_title %}{% trans "Contacts" %} | {{ block.super }}{% endblock %}

{% block content %}

<ul class="nav nav-tabs">
    <li role="presentation" class="active"><a href="{% url 'squattour:contacts' %}">{% trans "Contacts list" %}</a></li>
    <li role="presentation"><a href="{% url 'squattour:import' %}">{% trans "Import" %}</a></li>
</ul>

{% if contacts %}
<table class="table table-striped table-hover">
    <thead>
        <tr>
            <th>{% trans "Name" %}</th>
            <th>{% trans "Address" %}</th>
            <th>{% trans "Origin" %}</th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        {% for contact in contacts %}
        <tr>
            <td>{{ contact.name }}</td>
            <td>{{ contact.best_address }}</td>
            <td>
                {% if contact.social_app %}
                    {{ contact.social_app.name }}
                {% else %}
                    {% trans "local" %}
                {% endif %}
            </td>
            <td>
                <form action="" method="post">
                    {% csrf_token %}
                    <input type="hidden" name="contact" value="{{ contact.id }}" />
                    {% if contact.show %}
                    <button class="btn btn-default" type="submit" name="action" value="hide">{% trans "Hide" %}</button>
                    {% else %}
                    <button class="btn btn-default" type="submit" name="action" value="show">{% trans "Show" %}</button>
                    {% endif %}
                    <!-- <button class="btn btn-default" type="submit" name="action" value="reimport">{% trans "Re-import" %}</button> -->
                </form>
            </td>
        </tr>
        {% endfor %}
    </tbody>
</table>

{% include "squattour/snippets/pagination.html" with page=contacts %}

{% else %}

<p>
    You don't have any imported contacts yet,
    <a href="{% url "squattour:import" %}">import some</a>.
</p>

{% endif %}

{% endblock %}

squattour/templates/squattour/import.html
{% extends "squattour/base.html" %}

{% load i18n %}
{% load staticfiles %}
{% load socialaccount %}

{% block head_title %}{% trans "Import" %} | {{ block.super }}{% endblock %}

{% block content %}

<ul class="nav nav-tabs">
    <li role="presentation"><a href="{% url 'squattour:contacts' %}">{% trans "Contacts list" %}</a></li>
    <li role="presentation" class="active"><a href="{% url 'squattour:import' %}">{% trans "Import" %}</a></li>
</ul>

{% if accounts %}
<h3>Existing connections</h3>
<p>You are connected with the following accounts:</p>

<table class="table import-connections">
    <thead>
        <tr>
            <th>{% trans "Service" %}</th>
            <th>{% trans "Account" %}</th>
            <th></th>
        </tr>
    </thead>
    <tbody>
    {% for base_account in accounts %}
        {% with base_account.get_provider_account as account %}
        <tr class="socialaccount_provider {{ base_account.provider }} {{ account.get_brand.id }}">
            <td>
                <img alt="{{account.get_brand.name}}:" src="{% static 'squattour/img/services/' %}{{ account.get_brand.id }}.png" />
                {{ account.get_brand.name }}
            </td>
            <td>{{ account }}</td>
            <td>
                <a href="{% url "squattour:import_social" account=base_account.id %}" class="btn btn-sm btn-primary">
                    <span class="glyphicon glyphicon-import"></span>
                    {% trans "Import" %}
                </a>
            </td>
        </tr>
        {% endwith %}
    {% endfor %}
    </tbody>
</table>


<p>
    You can delete contacts imported from an account by removing this account
    in <a href="{% url "socialaccount_connections" %}">your profile page</a>.
</p>

<hr />
{% endif %}

<h3>Add a connection</h3>
<p>You can connect to your accounts using the following providers:</p>
{% get_providers as socialaccount_providers %}
<ul class="socialaccount_providers list-inline">
  {% include "socialaccount/snippets/provider_list.html" with process="connect" %}
</ul>


{% endblock %}

squattour/templates/squattour/import_social.html
{% extends "squattour/base.html" %}
{% load staticfiles %}

{% block head_title %}Import | {{ block.super }}{% endblock %}

{% block content %}

<h1>Importing from {{ social_app.name }}</h1>

<ol id="imported">
</ol>

<p>
    <img id="spinner" alt="loading..." src="{% static "squattour/img/ajax-loader.gif" %}" />
</p>

{% csrf_token %}

{% endblock %}

{% block extra_body %}
<script>
    function worker() {
        $.getJSON({
            url: '{% url "squattour:poll_import_status" account=social_account.pk %}',
            success: function(data) {
                if (data.status === "done") {
                    window.location = '{% url "squattour:contacts" %}';
                } else {
                    var start = $("#imported li").length;
                    var newContacts = data.contacts.slice(start);
                    $.each(newContacts, function(index, value) {
                        $("<li>"+value+"</li>\n").hide().appendTo("#imported");
                    });
                    $("#imported li:hidden").slideDown().promise().done(function() {
                        $("html, body").animate({ scrollTop: $(document).height()-$(window).height() });
                    });
                }
            },
            complete: function() {
                // Schedule the next request when the current one's complete
                setTimeout(worker, 1000);
            }
        });
    }
    function start_import() {
        $.ajax({
            url: '{% url "squattour:poll_import_status" account=social_account.pk %}',
            method: "POST",
            headers: {
                'X-CSRFToken': $("input[name='csrfmiddlewaretoken']").val()
            },
            timeout: 300000,
            success: function(data) {
                window.location = '{% url "squattour:contacts" %}';
            }
        });
        setTimeout(worker, 2000);
    }
    $(function() {
        start_import();
    });
</script>
{% endblock %}

squattour/templates/squattour/index.html
{% extends "squattour/base.html" %}

{% block content %}
<div class="jumbotron">
  <h1>Squat Tour</h1>
  <p>Collect your friends' home addresses and plan your next vacation.</p>
  <p><a class="btn btn-info" href="http://gitlab.com/abompard/squattour" role="button">Learn more</a></p>
</div>

{% if not user.is_authenticated %}
<p><a href="{% url "socialaccount_connections" %}">Login</a> to import your contacts and create your friends' map.</p>
{% endif %}

{% endblock %}

squattour/templates/squattour/map.html
{% extends "squattour/base.html" %}

{% load i18n %}

{% block head_title %}Map | {{ block.super }}{% endblock %}

{% block extra_head %}
<style>
    #map {
        height: 500px;
    }
    #map .squattour-popup {
        overflow: auto;
    }
    #map .squattour-popup h1 {
        font-size: 105%;
        font-weight: bold;
        margin-top: 0;
    }
    #map .squattour-popup img.photo {
        float: left;
        margin-right: 10px;
        width: 50px;
        height: 50px;
    }
    #map .squattour-popup p {
        margin: 0;
    }
</style>
{% endblock %}

{% block content %}

    <div id="map"></div>

    <p class="controls">
        <div class="btn-group">
            <button type="button" class="btn btn-default btn-sm dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                <span class="glyphicon glyphicon-export"></span>
                {% trans "Export" %} <span class="caret"></span>
            </button>
            <ul class="dropdown-menu">
                <li><a href="{% url "squattour:export" fmt="kml" %}">{% trans "KML format" %}</a></li>
                <li><a href="{% url "squattour:export" fmt="json" %}">{% trans "GeoJSON format" %}</a></li>
            </ul>
        </div>

    {% block map_controls %}{% endblock %}
    </p>

{% endblock %}